### ISSUE TITLE
Attempt to Fix Deployment Issues

### ISSUE THREAD

**Issue by Hedgemon4** [COSC-499-W2023/year-long-project-team-3#278]
### Description
- Currently, our deployed application is unable to access AWS services.
- In order for our app to be able to access them, we need to migrate the deployment to EC2

### Tasks
- [x] Create dockerfile to build image of nextjs application
- [x] Create EC2 instance and deploy docker image to it
- [x] Create role and test that the application can access AWS resources
- [x] Update Github actions to automatically deploy to AWS
