### ISSUE TITLE
Deletion & recovery for videos

### ISSUE THREAD

**Issue by te-sa** [COSC-499-W2023/year-long-project-team-3#81]
Deleting recorded video (retracting submission) & recovering deleted video (with grace period)

### Tasks
- [x] #159 
- [ ] Trace uploaded cloud data and remove it from all buckets
- [ ] Create a new "Trash" tab and put deleted videos there
- [ ] Make a cronjob running every few minutes to check for videos need to be deleted
